# silkspawners.silk <- allows players to get spawners as long as they have the silk-touch enchantment on the tool they are using
# silkspawners.nosilk <- allows players to get spawners on break always